# Site settings
title: WebDevPhoenix
email: brad@azpixels.com
description: WebDevPhoenix provides a list of companies in Phoenix, Arizona that currently or might in the future, hire web developers. Even if a company isn't currently hiring, it's nice to know who's out there and what technologies they're using.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webdevphoenix.com" # the base hostname & protocol for your site
twitter_username: bradwestfall
github_username:  bradwestfall

# Build settings
markdown: kramdown

exclude:
  - bower_components/*.html

# Jekyll plugins to load
gems:
  - jekyll-sitemap
